;===============================================================================
;KIM KAPHWAN KOF 98 CREADO POR FACU-96
;ESTADO DEL CHAR 100%
;===============================================================================

[Remap]
x = x
y = y
z = z
a = a
b = b
c = c
s = s
                                                                                
;-SUPERS------------------------------------------------------------------------

[Command]
name = "¥¼¥í¾àëxøP»Ë½Å"
command = ~D, DB, D, DF, x+y
time = 35

[Command]
name = "¥¼¥í¾àëxøP»Ë½Å"
command = ~D, DB,D, DB, c
time = 25

[Command]
name =  "26"
command = ~D, F
time = 10

[Command]
name =  "hidden1"                  ;2600
command = ~D, B, F, c
time = 30

[Command]
name =  "hidden2"                  ;2800
command = ~D, F, D, B, c
time = 30

[Command]
name =  "hidden3"                  ;2700
command = ~D, F, D, F, c
time = 30

;---------------------------------Max-Mode-------------------------------------

[Command]
name =  "Super Comun"             ;2200
command = ~D, B, F, a+b
time = 30

;[Command]
;name =  "Super Comun"
;command = ~D, B, F, a
;time = 30

[Command]
name =  "Super Comun"
command = ~D, B, F, c
time = 30

[Command]
name =  "Super Comun Aire"         ;2210
command = ~D, B, F, a+b
time = 30

;[Command]
;name =  "Super Comun Aire"
;command = ~D, B, F, a
;time = 25

[Command]
name =  "Super Comun Aire"
command = ~D, B, F, c
time = 30

[Command]
name =  "Super Tembu"               ;2300
command = ~D, F, B, a+b
time = 30

;[Command]
;name =  "Super Tembu"
;command = ~D, F, B, b
;time = 30

[Command]
name =  "Super Tembu"
command = ~D, F, B, c
time = 30

[Command]
name =  "·ï»ÊÁÑ×¦½Å"                     ;2410
command = ~D, F, D, F, y
time = 30

[Command]
name =  "·ï»ÊÁÑ×¦½ÅMAX"                     ;2460
command = ~D, F, D, F, x+y
time = 30

[Command]
name =  "È«Ê½ÁÑ×¦ïwÌì½Å"                 ;2500
command = ~D, F, D, F, x
time = 30

;-ESPECIALES-------------------------------------------------------------------

[Command]
name =  "Especial Comun Corta"    ;2000
command = ~D, B, F, a
time = 30

[Command]
name =  "Especial Comun Larga"
command = ~D, B, F, b
time = 30

[Command]
name =  "Especial Comun Aire"     ;2001
command = ~D, B, F, a
time = 30

[Command]
name =  "Especial Comun Aire"
command = ~D, B, F, b
time = 30

[Command]
name =  "Especial Tembu"          ;2100
command = ~D, F, B, a
time = 30

[Command]
name =  "Especial Tembu"
command = ~D, F, B, b
time = 30

[Command]
name =  "·ï»Ë·ÉÌì½Å 2"          ;2510
command = ~D, F, D, F, a
time = 30

[Command]
name =  "·ï»Ë·ÉÌì½Å 2"          ;2510
command = ~D, F, D, F, b
time = 30

[Command]
name =  "·ï»Ë·ÉÌì½Å"              ;2060
command = ~D, F, D, F, a
time = 30

[Command]
name =  "·ï»Ë·ÉÌì½Å"
command = ~D, F, D, F, b
time = 30

;-PODERES-----------------------------------------------------------------------
[Command]
name = "·ÉÑàÕ¶EX"
command = ~F, D, F, a+b
time = 15

[Command]
name = "·ÉÏèÂäEX"
command = ~D, F, a+b
time = 15

[Command]
name = "°ÔÆø½ÅEX"
command = ~D, D, a+b
time = 15

[Command]
name = "°ëÔÂÕ¶EX"
command = ~D, B, a+b
time = 15

[Command]
name = "Á÷ÐÇÂäEX"
command = ~D, D, x+y
time = 15

[Command]
name = "¿ÕÉ°³¾EX"
command = ~F, D, F, x+y
time = 15

[Command]
name = "ÈýÁ¬»÷EX"
command = ~D, B, x+y
time = 15


;------------------------------------

[Command]
name = "236x"         ;840
command = ~B, D, F, x
time = 20

[Command]
name = "236x"
command = ~B, D, F, x
time = 20

[Command]
name = "Oriuken Corto"         ;F D F a [1020,1021]
command = ~F, D, F, a
time = 15

[Command]
name = "Oriuken Largo"         ;F D F b [1025,1026]
command = ~F, D, F, b
time = 15

[Command]
name = "Oriuken 3"         ;F D F b [1040,1041]
command = ~F, D, F, c
time = 15

[Command]
name = "Kuusajin 1"            ;D U x [1100]
command = ~F, D, F, x
time = 15

[Command]
name = "Kuusajin 1"            ;D U x [1100]
command = ~F, D, F, x
time = 15

[Command]
name = "Kuusajin 2"            ;D U y [1105]
command = ~F, D, F, y
time = 15

[Command]
name = "Kuusajin 2"            ;D U y [1105]
command = ~F, D, F, y
time = 15

[Command]
name = "Giro Patada Debil"     ;D B a [1200,1202]
command = ~D, B, a
time = 15

[Command]
name = "Giro Patada Fuerte"    ;D B b [1205,1207]
command = ~D, B, b
time = 15

;------------------------

[Command]
name = "Patada KOF-98"         ;D B x [1450 1455 1465]
command = ~D, B, x
time = 15

[Command]
name = "Patada KOF-98"         ;D B y [1450 1455 1462 1463]
command = ~D, B, y
time = 15

[Command]
name = "DBy"         ;D B y [1900]
command = ~D, B, y
time = 15

[Command]
name = "Level-1"
command = ~D, B, x
time = 15

[Command]
name = "Level-2"
command = ~D, B, y
time = 15

;------------------------

[Command]
name = "Hishou 1"           ;D F A [1305 1302]
command = ~D, F, a
time = 15

[Command]
name = "Hishou 2"           ;D F b [1300 1302]
command = ~D, F, b
time = 15

[Command]
name = "Hishou 3"            ;D F b 1380
command = ~D, F, x
time = 15

[Command]
name = "Hishou 3"            ;
command = ~F, D, F, y
time = 15

[Command]
name = "Traba Corta"        ;B F a [1600,1603]
command = ~D, D, x
time = 15

[Command]
name = "Traba Larga"        ;B F b [1605,1609]
command = ~D, D, y

[Command]
name = "Pisoton Debil"      ;D D a 1500
command = ~D, D, a
time = 15

[Command]
name = "Pisoton Fuerte"     ;D D b 1501
command = ~D, D, b
time = 15

[Command]
name = "×Æ»ðÒu1"     ;new 1800
command = ~D, F, y
time = 15

[Command]
name = "×Æ»ðÒu2"     ;new 1850
command = ~D, F, x
time = 15

[Command]
name = "×Æ»ðÒuEX"     ;new 3080
command = ~D, F, x+y
time = 15



[Command]
name = "ÅÅÆø»÷"     ;new 1900
command = ~D, B, c
time = 15







;-MOVIMIENTOS-------------------------------------------------------------------

[Command]
name = "FF"
command = F, F
time = 10

[Command]
name = "BB"
command = B, B
time = 10

;-------------------------------------------------------------------------------
[Command]
name = "fwd"
command = F
time = 1

[Command]
name = "back"
command = B
time = 1

[Command]
name = "up"
command = U
time = 1

[Command]
name = "down"
command = D
time = 1

[Command]
name = "recovery"
command = x+a
time = 1

[Command]
name = "recovery"
command = z
time = 1

[Command]
name = "rock"
command = a+y
time = 1

[Command]
name = "cd"
command = b+y
time = 1

[Command]
name = "ab"
command = a+x
time = 1

[Command]
name = "abc"
command = a+y
time = 1

;-------------------------------------------------------------------------------

[Command]
name = "down_a"
command = /$D,a
time = 1

[Command]
name = "down_b"
command = /$D,b
time = 1

;-------------------------------------------------------------------------------

[Command]
name = "a"
command = a
time = 1

[Command]
name = "b"
command = b
time = 1

[Command]
name = "c"
command = c
time = 1

[Command]
name = "hold_a"
command = /$a
time = 1

[Command]
name = "hold_b"
command = /$b
time = 1

[Command]
name = "hold_c"
command = /$c
time = 1

[Command]
name = "hold_x"
command = /$x
time = 1

[Command]
name = "hold_y"
command = /$y
time = 1

[Command]
name = "hold_z"
command = /$z
time = 1

[Command]
name = "x"
command = x
time = 1

[Command]
name = "y"
command = y
time = 1

[Command]
name = "z"
command = z
time = 1

[Command]
name = "start"
command = s
time = 1

;-------------------------------------------------------------------------------

[Command]
name = "holdfwd"
command = /$F
time = 1

[Command]
name = "holdback"
command = /$B
time = 1

[Command]
name = "holdup"
command = /$U
time = 1

[Command]
name = "holddown"
command = /$D
time = 1

[Command]
name = "holddownfwd"
command = /$DF
time = 1

[Command]
name = "longjump"
command = ~D, $U
time = 11

[Command]
name = "!longjump"
command = ~10$D, $U
time = 20

[Command]
name = "charge 1"
command = /a

[Command]
name = "charge 2"
command = /y

[Command]
name = "MAX-1"
command = /a

[Command]
name = "MAX-2"
command = /y

;===============================================================================
[Statedef -1]
;===============================================================================
[state -1]
type = null;varset
var(55) = 1
trigger1 = (ctrl && helper(10002),command = "Patada KOF-98") || (movecontact && command = "Patada KOF-98")
ignorehitpause = 1

[state -1]
type = null;varset
var(55) = 0
trigger1 = helper(10002),command != "Patada KOF-98"
ignorehitpause = 1

[state -1]
type = varset
var(55) = helper(10000),var(23)
trigger1 = roundstate = 2
[state -1]
type = varset
var(55) = helper(10000),var(23) + (helper(10000),var(22) = 3)*10
trigger1 = roundstate = 2


;================================================

;-------------------------------------------------------------------------------
; Super Cancel


;CounterMode (!movecontact
[state -1]
type = changestate
value = helper(10002),var(17)
triggerall = var(59) = 0 && ishelper = 0
triggerall = power >= 1000 || var(7) > 0
triggerall = helper(10000),var(3) = 2
triggerall = helper(10002),var(17) > 0
triggerall = statetype != A
triggerall = stateno != helper(10002),var(17)
;--------------------------------------------
trigger1 = stateno = 1020 || stateno = 1025 || stateno = 1040
trigger2 = stateno = 1202 || stateno = 1207
trigger3 = stateno = 1465
trigger4 = stateno = [1500,1501]
trigger5 = stateno = [1601,1602]
trigger6 = stateno = [1605,1606]
trigger7 = stateno = 1800
trigger8 = stateno = 1850 || stateno = 1855
;--------------------------------------------
ignorehitpausetime = 1

;land
[state -1]
type = changestate
value = helper(10002),var(18)
triggerall = var(59) = 0 && ishelper = 0
triggerall = power >= 1000
triggerall = helper(10000),var(3) = 1;[1,2]
triggerall = helper(10002),var(18) > 0
triggerall = statetype != A
triggerall = stateno != helper(10002),var(18)
triggerall = time > 5
;--------------------------------------------
;±¸·ÝÓÃ
;trigger = stateno = 
trigger1 = stateno = [2005,2006]
trigger2 = stateno = 2008
trigger3 = stateno = [2020,2021]
;--------------------------------------------
ignorehitpausetime = 1


;air
[state -1]
type = changestate
value = helper(10002),var(18)
triggerall = var(59) = 0 && ishelper = 0
triggerall = power >= 1000
triggerall = helper(10000),var(3) = 1;[1,2]
triggerall = helper(10002),var(18) > 0
triggerall = statetype = A
triggerall = stateno != helper(10002),var(18)
triggerall = time > 5
;--------------------------------------------
;±¸·ÝÓÃ
;trigger = stateno = 
trigger1 = stateno = [2005,2006]
trigger2 = stateno = [2008,2009]
trigger3 = stateno = [2020,2021]
trigger4 = stateno = [2105,2106]
;--------------------------------------------
ignorehitpausetime = 1


;CounterMode/SuperCancel (movecontact
[state -1]
type = changestate
value = helper(10002),var(17)
triggerall = var(59) = 0 && ishelper = 0
triggerall = power >= 1000 || var(7) > 0
triggerall = helper(10000),var(3) = [1,2]
triggerall = helper(10002),var(17) > 0
triggerall = statetype != A
triggerall = (movecontact) || helper(10000),var(5) > 0
triggerall = stateno != helper(10002),var(17)
;--------------------------------------------
trigger1 = stateno = 1020 || stateno = 1025 || stateno = 1040
trigger2 = stateno = 1202 || stateno = 1207
trigger3 = stateno = 1465
trigger4 = stateno = [1500,1501]
trigger5 = stateno = [1601,1602]
trigger6 = stateno = [1605,1606]
trigger7 = stateno = 1800
trigger8 = stateno = 1850 || stateno = 1855
;--------------------------------------------
ignorehitpausetime = 1


;CounterMode/SuperCancel (movecontact
;Air
[state -1]
type = changestate
value = helper(10002),var(17)
triggerall = var(59) = 0 && ishelper = 0
triggerall = power >= 1000 || var(7) > 0
triggerall = helper(10000),var(3) = [1,2]
triggerall = helper(10002),var(17) > 0
triggerall = statetype = A
triggerall = (movecontact) || helper(10000),var(5) > 0
triggerall = stateno != helper(10002),var(17)
;--------------------------------------------
trigger1 = stateno = [1026,1027]
trigger2 = stateno = 1041
trigger3 = stateno = 1101 || stateno = 1106
trigger4 = stateno = 1201 || stateno = 1206 || stateno = 1210
trigger5 = stateno = 1301 || stateno = 1381
trigger6 = stateno = 1461 || stateno = 1463
trigger7 = stateno = 1471
trigger8 = stateno = 1603 || stateno = 1608
;--------------------------------------------
trigger9 = stateno = 622
ignorehitpausetime = 1

;land
[state -1]
type = changestate
value = helper(10002),var(12)
triggerall = var(59) = 0 && ishelper = 0
triggerall = var(7) > 0
triggerall = helper(10000),var(3) != 2
triggerall = helper(10000),var(2) = 1
triggerall = helper(10002),var(12) > 0
triggerall = helper(10002),var(17) <= 0
triggerall = statetype != A
triggerall = (movecontact) || ((stateno = [0,999]) && (movetype = A || time < 15))
triggerall = stateno != helper(10002),var(12)
;--------------------------------------------
trigger1 = (stateno = [0,999]) && (movetype = A || time < 15)
trigger2 = stateno = 1020 || stateno = 1025 || stateno = 1040
trigger3 = stateno = 1450
trigger4 = stateno =  1455
trigger5 = stateno =  1465
trigger6 = stateno =  1850
trigger7 = stateno =  1855
trigger8 = stateno =  1800
trigger9 = stateno =  1202
trigger10 = stateno =  1207
trigger11 = stateno = [1601,1602]
trigger12 = stateno = [1606,1607]
trigger13 = stateno = [1500,1501]
;
;ignorehitpausetime = 1
ignorehitpause = 1

;land
[state -1]
type = changestate
value = helper(10002),var(12)
triggerall = var(59) = 0 && ishelper = 0
triggerall = var(7) > 0
triggerall = helper(10000),var(3) != 2
triggerall = helper(10000),var(2) = 1
triggerall = helper(10002),var(12) > 0
triggerall = helper(10002),var(17) <= 0
triggerall = statetype != A
triggerall = stateno != helper(10002),var(12)
;--------------------------------------------
triggerall = numtarget
trigger1 = stateno = 1202
trigger2 = stateno = 1207
;
;ignorehitpausetime = 1
ignorehitpause = 1

;air
[state -1]
type = changestate
value = helper(10002),var(12)
triggerall = var(59) = 0 && ishelper = 0
triggerall = var(7) > 0
triggerall = helper(10000),var(3) != 2
triggerall = helper(10000),var(2) = 1
triggerall = helper(10002),var(12) > 0
triggerall = helper(10002),var(17) <= 0
triggerall = statetype = A
triggerall = (movecontact) || ((stateno = [0,999]) && (movetype = A || time < 15))
triggerall = stateno != helper(10002),var(12)
;
triggerall = (helper(10002),var(12) = [1300,1380]) || helper(10002),var(12) = 1210
;--------------------------------------------
trigger1 = (stateno = [0,999]) && (movetype = A || time < 15) && movecontact
trigger2 = stateno = [1020,1027]
trigger3 = stateno = [1040,1041]
trigger4 = stateno = [1101,1106]
trigger5 = stateno = [1470,1471]
trigger6 = stateno =  [1461,1463]
trigger7 = stateno =  [1201,1210]
trigger8 = stateno = [1603,1608]
;--------------------------------------------
trigger9 = stateno = 622
ignorehitpause = 1


;-------------------------------------------------------------------
[state -1,TEST]
type = changestate
value = 1940
triggerall = !var(59)
triggerall = command = "start"
trigger1 = ctrl
ignorehitpausetime = 1


[state -1]
type = changestate
value = 2800
triggerall = !var(59)
triggerall = power >= 2000 || (power >= 1000 && prevstateno != [0,1999])
triggerall = statetype != A
triggerall = helper(10002),command = "hidden3"
trigger1 = ctrl
trigger2 = stateno = 2005 && time > 10
trigger3 = stateno = 2008 && time > 10
trigger4 = stateno = 2205 && time > 10
trigger5 = stateno = 2208 && time > 10
trigger6 = stateno = 2009 && time > 10
trigger7 = stateno = 2020 && time > 10

[state -1]
type = changestate
value = 2650
triggerall = !var(59)
triggerall = power >= 2000 || (power >= 1000 && prevstateno != [0,1999])
triggerall = statetype != A
triggerall = helper(10002),command = "¥¼¥í¾àëxøP»Ë½Å"
trigger1 = ctrl
trigger2 = stateno = 2005 && time > 10
trigger3 = stateno = 2008 && time > 10
trigger4 = stateno = 2205 && time > 10
trigger5 = stateno = 2208 && time > 10
trigger6 = stateno = 2009 && time > 10
trigger7 = stateno = 2020 && time > 10

[state -1]
type = changestate
value = 2650
triggerall = !var(59)
triggerall = power >= 2000
triggerall = statetype != A
triggerall = command = "¥¼¥í¾àëxøP»Ë½Å"
trigger1 = ctrl
Trigger2 = stateno = 205 && (movecontact = [1,3])
Trigger3 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger4 = stateno = 215 && (movecontact = [1,3])
Trigger5 = stateno = 225 && (movecontact = [1,3])
Trigger6= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger7= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger8= stateno = 400 && (movecontact = [1,3])
Trigger9= stateno = 420 && (movecontact = [1,3])

[state -1]
type = changestate
value = 2600
triggerall = !var(59)
triggerall = power >= 2000 || (power >= 1000 && prevstateno != [0,1999])
triggerall = statetype != A
triggerall = helper(10002),command = "hidden1"
trigger1 = ctrl
trigger2 = stateno = 2005 && time > 10
trigger3 = stateno = 2008 && time > 10
trigger4 = stateno = 2205 && time > 10
trigger5 = stateno = 2208 && time > 10
trigger6 = stateno = 2009 && time > 10
trigger7 = stateno = 2020 && time > 10

[state -1]
type = changestate
value = 2700
triggerall = !var(59)
triggerall = power >= 2000 || (power >= 1000 && prevstateno != [0,1999])
triggerall = statetype != A
triggerall = helper(10002),command = "hidden2"
trigger1 = ctrl
trigger2 = stateno = 2005 && time > 10
trigger3 = stateno = 2008 && time > 10
trigger4 = stateno = 2205 && time > 10
trigger5 = stateno = 2208 && time > 10
trigger6 = stateno = 2009 && time > 10
trigger7 = stateno = 2020 && time > 10

;-------------------------------------------------------------------------------

;Super Comun
[State -1]
type = ChangeState
value = 2200
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Super Comun") || (movecontact && command = "Super Comun")
triggerall = (var(7) > 0 && power >= 1000) || power >= 2000
triggerall = helper(10000),var(3) != 2 && helper(10000),var(4) = 0
trigger1 = ctrl
Trigger2 = stateno = 205 && (movecontact = [1,3])
Trigger3 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger4 = stateno = 215 && (movecontact = [1,3])
Trigger5 = stateno = 225 && (movecontact = [1,3])
Trigger6= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger7= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger8= stateno = 400 && (movecontact = [1,3])
Trigger9= stateno = 420 && (movecontact = [1,3])
Trigger10 = stateno = 1500 && (movecontact = [1,3])
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Super Comun Aire
[State -1,]
type = ChangeState
value = 2210
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = ((ctrl || stateno = 950 || stateno = 50) && helper(10002),command = "Super Comun Aire") || (movecontact && command = "Super Comun Aire")
triggerall = (var(7) > 0 && power >= 1000) || power >= 2000
triggerall = helper(10000),var(3) != 2 && helper(10000),var(4) = 0
trigger1 = ctrl || stateno = 950 || stateno = 50
Trigger2 = stateno = 246 && (movecontact = [1,3])
Trigger3 = stateno = 600 && (movecontact = [1,3])
Trigger4 = stateno = 610 && (movecontact = [1,3])
Trigger5 = stateno = 620 && (movecontact = [1,3])
Trigger6 = stateno = 630 && (movecontact = [1,3])
Trigger7 = stateno = 622 && (movecontact = [1,3])
trigger8 = (stateno = 310 && movecontact = [1,3]) || stateno = 320
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Super Comun
[State -1]
type = ChangeState
value = 2460
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "·ï»ÊÁÑ×¦½ÅMAX") || (movecontact && command = "·ï»ÊÁÑ×¦½ÅMAX")
triggerall = (var(7) > 0 && power >= 1000) || power >= 2000
;triggerall = helper(10000),var(14) = 1 || helper(10000),var(14) = 3 || helper(10000),var(14) = 5
triggerall = helper(10000),var(5) > 0
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 410 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = ChangeState
value = 2460
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "·ï»ÊÁÑ×¦½ÅMAX"
triggerall = helper(10002),var(10) = 2626
;------------------------------------
triggerall = (var(7) > 0 && power >= 1000) || power >= 2000
;triggerall = helper(10000),var(14) = 3 || helper(10000),var(14) = 5
triggerall = helper(10000),var(5) > 0
;--------------------------------------------------
trigger1 = stateno = 1455 && (movecontact = [1,3])
trigger2 = stateno = 1465 && (movecontact = [1,3])
trigger3 = stateno = 1463 && (movecontact = [1,3])
trigger4 = stateno = 1461 && (movecontact = [1,3])
trigger5 = stateno = 1470 && (movecontact = [1,3])
trigger6 = stateno = 1471 && (movecontact = [1,3])
trigger7 = stateno = 1101 && (movecontact = [1,3])
trigger8 = stateno = 1106 && (movecontact = [1,3])
trigger9 = stateno = 1601 && (movecontact = [1,3])
trigger10 = stateno = 1603 && (movecontact = [1,3])
trigger11 = stateno = 1606 && (movecontact = [1,3])
trigger12 = stateno = 1608 && (movecontact = [1,3])
trigger13 = (stateno = [1850,1855]) && (movecontact = [1,3])
trigger14 = stateno = 1800 && (movecontact = [1,3])
trigger15 = stateno = 1201 && (movecontact = [1,3])
trigger16 = stateno = 1202 && (movecontact = [1,3])
trigger17 = stateno = 1206 && (movecontact = [1,3])
trigger18 = stateno = 1207 && (movecontact = [1,3])
trigger19 = stateno = 1500 && (movecontact = [1,3])
trigger20 = stateno = 1501 && (movecontact = [1,3])
trigger21 = stateno = 1021 && (movecontact = [1,3])
trigger22 = stateno = 1025 && (movecontact = [1,3])
trigger23 = stateno = 1026 && (movecontact = [1,3])
trigger24 = stateno = 1027 && (movecontact = [1,3])
trigger25 = stateno = 622 && (movecontact = [1,3])
;--------------------------------------------------
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Super Comun
[State -1]
type = ChangeState
value = 2450
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = (ctrl && helper(10002),command = "·ï»ÊÁÑ×¦½Å") || (movecontact && command = "·ï»ÊÁÑ×¦½Å")
triggerall = statetype != A
triggerall = (var(7) <= 0 && power >= 1000) || (var(7) > 0 && helper(10000),var(3) = [1,2])
trigger1 = ctrl
Trigger2 = stateno = 205 && (movecontact = [1,3])
Trigger3 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger4 = stateno = 215 && (movecontact = [1,3])
Trigger5 = stateno = 225 && (movecontact = [1,3])
Trigger6= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger7= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger8= stateno = 400 && (movecontact = [1,3])
Trigger9= stateno = 420 && (movecontact = [1,3])
Trigger10 = stateno = 1500 && (movecontact = [1,3])
ignorehitpausetime = 1

;-------------------------------------------------------------------------------

;Super Comun
[State -1]
type = ChangeState
value = 2500
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = (ctrl && helper(10002),command = "È«Ê½ÁÑ×¦ïwÌì½Å") || (movecontact && command = "È«Ê½ÁÑ×¦ïwÌì½Å")
triggerall = statetype != A
triggerall = (var(7) <= 0 && power >= 1000) || (var(7) > 0 && helper(10000),var(3) = [1,2])
trigger1 = ctrl
Trigger2 = stateno = 205 && (movecontact = [1,3])
Trigger3 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger4 = stateno = 215 && (movecontact = [1,3])
Trigger5 = stateno = 225 && (movecontact = [1,3])
Trigger6= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger7= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger8= stateno = 400 && (movecontact = [1,3])
Trigger9= stateno = 420 && (movecontact = [1,3])
Trigger10 = stateno = 1500 && (movecontact = [1,3])
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Super Tembu
[State -1,]
type = ChangeState
value = 2300
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = ((ctrl || stateno = 950 || stateno = 50) && helper(10002),command = "Super Tembu") || (movecontact && command = "Super Tembu")
triggerall = (var(7) > 0 && power >= 1000) || power >= 2000
triggerall = helper(10000),var(3) != 2 && helper(10000),var(4) = 0
trigger1 = ctrl || stateno = 950 || stateno = 50
Trigger2 = stateno = 246 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger3 = stateno = 600 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger4 = stateno = 610 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger5 = stateno = 620 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger6 = stateno = 630 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger7 = stateno = 622 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
trigger8 = (stateno = 310 && movecontact = [1,3]) || stateno = 320
trigger9 = stateno = 640 && (movecontact = [1,3])
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;cancelmode on
;200/220/230/235/410 enable

;Especial Comun Corta
[State -1]
type = ChangeState
value = 2000
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Especial Comun Corta") || (movecontact && command = "Especial Comun Corta")
triggerall = (var(7) <= 0 && power >= 1000) || (var(7) > 0 && helper(10000),var(3) = [1,2])
trigger1 = ctrl
Trigger2 = stateno = 205 && (movecontact = [1,3])
Trigger3 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger4 = stateno = 215 && (movecontact = [1,3])
Trigger5 = stateno = 225 && (movecontact = [1,3])
Trigger6= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger7= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger8= stateno = 400 && (movecontact = [1,3])
Trigger9= stateno = 420 && (movecontact = [1,3])
Trigger10 = stateno = 1500 && (movecontact = [1,3])
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Especial Comun Larga
[State -1]
type = ChangeState
value = 2015
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Especial Comun Larga") || (movecontact && command = "Especial Comun Larga")
triggerall = (var(7) <= 0 && power >= 1000) || (var(7) > 0 && helper(10000),var(3) = [1,2])
trigger1 = ctrl
Trigger2 = stateno = 205 && (movecontact = [1,3])
Trigger3 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger4 = stateno = 215 && (movecontact = [1,3])
Trigger5 = stateno = 225 && (movecontact = [1,3])
Trigger6= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger7= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger8= stateno = 400 && (movecontact = [1,3])
Trigger9= stateno = 420 && (movecontact = [1,3])
Trigger10 = stateno = 1500 && (movecontact = [1,3])
ignorehitpausetime = 1


;-------------------------------------------------------------------------------
;Especial Comun Aire
[State -1,]
type = ChangeState
value = 2001
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = ((ctrl || stateno = 950 || stateno = 50) && helper(10002),command = "Especial Comun Aire") || (movecontact && command = "Especial Comun Aire")
triggerall = (var(7) <= 0 && power >= 1000) || (var(7) > 0 && helper(10000),var(3) = [1,2])
trigger1 = ctrl || stateno = 950 || stateno = 50
Trigger2 = stateno = 246 && movecontact = [1,3]
Trigger3 = stateno = 600 && movecontact = [1,3]
Trigger4 = stateno = 610 && movecontact = [1,3]
Trigger5 = stateno = 620 && movecontact = [1,3]
Trigger6 = stateno = 630 && movecontact = [1,3]
Trigger7 = stateno = 622 && movecontact = [1,3]
trigger8 = (stateno = 310 && movecontact = [1,3]) || stateno = 320
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Especial Tembu
[State -1,]
type = ChangeState
value = 2100
triggerall = var(59) = 0
triggerall = ((ctrl || stateno = 950 || stateno = 50) && helper(10002),command = "Especial Tembu") || (movecontact && command = "Especial Tembu")
triggerall = (var(7) <= 0 && power >= 1000) || (var(7) > 0 && helper(10000),var(3) = [1,2])
trigger1 = statetype = A
trigger1 = ctrl || stateno = 950 || stateno = 50
Trigger2 = stateno = 246 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger3 = stateno = 600 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger4 = stateno = 610 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger5 = stateno = 620 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger6 = stateno = 630 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
trigger7 = stateno = 621 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
trigger8 = stateno = 622 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
trigger9 = (stateno = 310 && movecontact = [1,3]) || stateno = 320
trigger10 = stateno = 640 && (movecontact = [1,3])
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Especial Tembu
[State -1,]
type = ChangeState
value = 2510
triggerall = var(59) = 0
triggerall = (ctrl && helper(10002),command = "·ï»Ë·ÉÌì½Å 2") || (movecontact && command = "·ï»Ë·ÉÌì½Å 2")
triggerall = (var(7) > 0 && ((power < 1000 && ((helper(10000),var(14) = 3) || (helper(10000),var(14) = 5))) || helper(10000),var(14) = 2)) || (var(7) <= 0 && power >= 1000)
trigger1 = statetype = A
trigger1 = ctrl
Trigger2 = stateno = 246 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger3 = stateno = 600 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger4 = stateno = 610 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger5 = stateno = 620 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
Trigger6 = stateno = 630 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
trigger7 = stateno = 621 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
trigger8 = stateno = 622 && (movecontact = [1,3]) && var(7) > 0 && helper(10000),var(14) = 5
ignorehitpausetime = 1

[State -1]
type = ChangeState
value = 2510
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = command = "·ï»Ë·ÉÌì½Å 2"
triggerall = helper(10002),var(10) = 2626
;-------------------------------------
triggerall = var(7) > 0 && ((power < 1000 && ((helper(10000),var(14) = 3) || (helper(10000),var(14) = 5))) || helper(10000),var(14) = 2)
;--------------------------------------------------
trigger1 = stateno = 1455 && (movecontact = [1,3])
trigger2 = stateno = 1465 && (movecontact = [1,3])
trigger3 = stateno = 1463 && (movecontact = [1,3])
trigger4 = stateno = 1461 && (movecontact = [1,3])
trigger5 = stateno = 1470 && (movecontact = [1,3])
trigger6 = stateno = 1471 && (movecontact = [1,3])
trigger7 = stateno = 1101 && (movecontact = [1,3])
trigger8 = stateno = 1106 && (movecontact = [1,3])
trigger9 = stateno = 1601 && (movecontact = [1,3])
trigger10 = stateno = 1603 && (movecontact = [1,3])
trigger11 = stateno = 1606 && (movecontact = [1,3])
trigger12 = stateno = 1608 && (movecontact = [1,3])
trigger13 = (stateno = [1850,1855]) && (movecontact = [1,3])
trigger14 = stateno = 1800 && (movecontact = [1,3])
trigger15 = stateno = 1201 && (movecontact = [1,3])
trigger16 = stateno = 1202 && (movecontact = [1,3])
trigger17 = stateno = 1206 && (movecontact = [1,3])
trigger18 = stateno = 1207 && (movecontact = [1,3])
trigger19 = stateno = 1500 && (movecontact = [1,3])
trigger20 = stateno = 1501 && (movecontact = [1,3])
trigger21 = stateno = 1021 && (movecontact = [1,3])
trigger22 = stateno = 1025 && (movecontact = [1,3])
trigger23 = stateno = 1026 && (movecontact = [1,3])
trigger24 = stateno = 1027 && (movecontact = [1,3])
trigger25 = stateno = 622 && (movecontact = [1,3])
trigger26 = stateno = 1301 && movecontact
trigger27 = stateno = 1381
;--------------------------------------------------
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 2510
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = helper(10000),var(14) != 1 && helper(10000),var(14) != 4
triggerall = power < 1000 || helper(10000),var(14) = 2
;----------------------------
trigger1 = ctrl 
trigger1 = var(7) > 0
trigger1 = command = "·ï»Ë·ÉÌì½Å 2"
;----------------------------
trigger2 = (movecontact = [1,3])
trigger2 = var(7) > 0
trigger2 = helper(10002),var(3)  = 4
ignorehitpausetime = 1
;-------------------------------------------------------------------------------

;Especial Tembu
[State -1,]
type = ChangeState
value = 2060
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = power >= 1000 
triggerall = (ctrl && helper(10002),command = "·ï»Ë·ÉÌì½Å") || (movecontact && command = "·ï»Ë·ÉÌì½Å")
triggerall = statetype != A
triggerall = (var(7) <= 0 && power >= 1000) || (var(7) > 0 && helper(10000),var(3) = [1,2])
trigger1 = ctrl
Trigger2 = stateno = 205 && (movecontact = [1,3])
Trigger3 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger4 = stateno = 215 && (movecontact = [1,3])
Trigger5 = stateno = 225 && (movecontact = [1,3])
Trigger6= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger7= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger8= stateno = 400 && (movecontact = [1,3])
Trigger9= stateno = 420 && (movecontact = [1,3])
Trigger10 = stateno = 1500 && (movecontact = [1,3])
ignorehitpausetime = 1

;-------------------------------------------------------------------------------


;[state -1]
;type = changestate
;value = helper(10002),var(9)
;triggerall = var(59) = 0
;triggerall = helper(10002),var(9) > 0
;triggerall = statetype != A
;triggerall = helper(10000),var(4) != 0
;triggerall = numtarget(1203) > 0
;trigger1 = stateno = 1202 && animelem = 2
;ignorehitpausetime = 1

[State -1]
type = Explod
triggerall = movecontact
trigger1 = stateno = [1201,1202]
anim = 9999
id = 1200
remove = 1
removetime = -1
sprpriority = -2
pos = 0,0
postype = p1
bindtime = 0
ownpal = 1
scale = 0,0
IgnoreHitPause = 1

[state -1]
type = RemoveExplod
id = 1200
trigger1 = stateno != [1201,1202]
IgnoreHitPause = 1


[State -1]
type = Explod
triggerall = movecontact
trigger1 = stateno = [1601,1602]
trigger2 = stateno = [1606,1607]
anim = 9999
id = 1600
remove = 1
removetime = -1
sprpriority = -2
pos = 0,0
postype = p1
bindtime = 0
ownpal = 1
scale = 0,0
IgnoreHitPause = 1

[state -1]
type = RemoveExplod
id = 1600
trigger1 = stateno != [1601,1602]
trigger1 = stateno != [1606,1607]
IgnoreHitPause = 1

;================================================
;========  hvar(4) set for SuperCancel  =========
;================================================


[state -1]
type = changestate
value = 3010
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0 && power >= 1000
triggerall = statetype != A
trigger1 = helper(10002),command = "·ÉÑàÕ¶EX"
trigger1 = ctrl
trigger2 = command = "·ÉÑàÕ¶EX"
trigger2 = stateno = [200,1999]
trigger2 = (movecontact = [1,3])
ignorehitpausetime = 1

[state -1]
type = changestate
value = 3020
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0 && power >= 1000
triggerall = statetype != A
trigger1 = helper(10002),command = "°ÔÆø½ÅEX"
trigger1 = ctrl
trigger2 = command = "°ÔÆø½ÅEX"
trigger2 = stateno = [200,1999]
trigger2 = (movecontact = [1,3])
ignorehitpausetime = 1

[state -1]
type = changestate
value = 3030
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0 && power >= 1000
triggerall = statetype != A
trigger1 = helper(10002),command = "°ëÔÂÕ¶EX"
trigger1 = ctrl
trigger2 = command = "°ëÔÂÕ¶EX"
trigger2 = stateno = [200,1999]
trigger2 = (movecontact = [1,3])
ignorehitpausetime = 1

[state -1]
type = changestate
value = 3035
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0 && power >= 1000
triggerall = statetype = A
trigger1 = helper(10002),command = "°ëÔÂÕ¶EX"
trigger1 = ctrl || stateno = 950 || stateno = 50
trigger2 = command = "°ëÔÂÕ¶EX"
trigger2 = stateno = [200,1999]
trigger2 = (movecontact = [1,3])
trigger3 = helper(10002),command = "°ëÔÂÕ¶EX"
trigger3 = stateno = 106
ignorehitpausetime = 1

[state -1]
type = changestate
value = 3040
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0 && power >= 1000
triggerall = statetype = A
trigger1 = helper(10002),command = "·ÉÏèÂäEX"
trigger1 = ctrl || stateno = 950 || stateno = 50
trigger2 = command = "·ÉÏèÂäEX"
trigger2 = stateno = [200,1999]
trigger2 = (movecontact = [1,3])
trigger3 = helper(10002),command = "·ÉÏèÂäEX"
trigger3 = stateno = 106
ignorehitpausetime = 1

[state -1]
type = changestate
value = 3050
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0 && power >= 1000
triggerall = statetype != A
trigger1 = helper(10002),command = "¿ÕÉ°³¾EX"
trigger1 = ctrl
trigger2 = command = "¿ÕÉ°³¾EX"
trigger2 = stateno = [200,1999]
trigger2 = (movecontact = [1,3])
ignorehitpausetime = 1

[state -1]
type = changestate
value = 3060
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0 && power >= 1000
triggerall = statetype  != A
trigger1 = helper(10002),command = "Á÷ÐÇÂäEX"
trigger1 = ctrl
trigger2 = command = "Á÷ÐÇÂäEX"
trigger2 = stateno = [200,1999]
trigger2 = (movecontact = [1,3])
ignorehitpausetime = 1

[state -1]
type = changestate
value = 3070
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0 && power >= 1000
trigger1 = helper(10002),command = "ÈýÁ¬»÷EX"
trigger1 = ctrl && statetype != A
trigger2 = command = "ÈýÁ¬»÷EX"
trigger2 = stateno = [1400,1499]
trigger2 = movecontact = [1,2]
trigger3 = command = "ÈýÁ¬»÷EX"
trigger3 = stateno = [200,1999]
trigger3 = (movecontact = [1,3])
ignorehitpausetime = 1

[state -1]
type = changestate
value = 3080
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0 && power >= 1000
triggerall = statetype  != A
trigger1 = helper(10002),command = "×Æ»ðÒuEX"
trigger1 = ctrl
trigger2 = command = "×Æ»ðÒuEX"
trigger2 = stateno = [200,1999]
trigger2 = (movecontact = [1,3])
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Oriuken Corto
[State -1]
type = ChangeState
value = 1020
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Oriuken Corto") || (movecontact && command = "Oriuken Corto")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1020
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Oriuken Corto"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Oriuken Largo
[State -1]
type = ChangeState
value = 1025
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Oriuken Largo") || (movecontact && command = "Oriuken Largo")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1025
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Oriuken Largo"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1


;---------------------------------------------------------------

;-------------------------------------------------------------------------------
;Oriuken Largo
[State -1]
type = ChangeState
value = 1040
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Oriuken 3") || (movecontact && command = "Oriuken 3")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1


;---------------------------------------------------------------

;Pisoton Debil
[State -1]
type = ChangeState
value = 1500
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Pisoton Debil") || (movecontact && command = "Pisoton Debil")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[state -1]
type = changestate
value = 1500
triggerall = var(59) = 0
triggerall = command = "holdfwd"
triggerall = command = "c"
triggerall = statetype != A
triggerall = statetype != L
trigger1 = stateno = [200,420]
trigger1 = (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1500
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Pisoton Debil"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1


;Pisoton Fuerte
[State -1]
type = ChangeState
value = 1501
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Pisoton Fuerte") || (movecontact && command = "Pisoton Fuerte")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
trigger15= stateno = 1465 && (movecontact = [1,3])
trigger15 = animelem = 10,>0
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1501
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Pisoton Fuerte"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

;-------------------------------------------------------------------------------
;Traba Corta
[State -1]
type = ChangeState
value = 1600
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Traba Corta") || (movecontact && command = "Traba Corta")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1600
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Traba Corta"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

;Traba Larga
[State -1]
type = ChangeState
value = 1605
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Traba Larga") || (movecontact && command = "Traba Larga")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1605
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Traba Larga"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

;Kuusajin 1
[State -1]
type = ChangeState
value = 1100
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Kuusajin 1") || (movecontact && command = "Kuusajin 1")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1100
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Kuusajin 1"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

;Kuusajin 2
[State -1]
type = ChangeState
value = 1105
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Kuusajin 2") || (movecontact && command = "Kuusajin 2")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1105
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Kuusajin 2"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

;Giro Patada Debil 
[State -1]
type = ChangeState
value = 1200
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Giro Patada Debil") || (movecontact && command = "Giro Patada Debil")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1200
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Giro Patada Debil"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

;Giro Patada Fuerte
[State -1]
type = ChangeState
value = 1205
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Giro Patada Fuerte") || (movecontact && command = "Giro Patada Fuerte")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1205
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Giro Patada Fuerte"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

;Giro Patada Fuerte
[State -1]
type = ChangeState
value = 1210
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0
triggerall = statetype = A
triggerall = (movecontact && command = "Giro Patada Fuerte") || helper(10002),command = "Giro Patada Fuerte"
trigger1 = ctrl
trigger2 = stateno = 950 || stateno = 50
trigger3 = stateno = 246 && movecontact
trigger4 = stateno = 310 && movecontact
trigger5 = stateno = 320 && movecontact
trigger6 = stateno = 106
ignorehitpausetime = 1

;Giro Patada Fuerte
[State -1]
type = ChangeState
value = 1210
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0
triggerall = statetype = A
triggerall = (movecontact && command = "Giro Patada Debil") || helper(10002),command = "Giro Patada Debil"
trigger1 = ctrl
trigger2 = stateno = 950 || stateno = 50
trigger3 = stateno = 246 && movecontact
trigger4 = stateno = 310 && movecontact
trigger5 = stateno = 320 && movecontact
ignorehitpausetime = 1


;Hishou 1
[State -1]
type = ChangeState
value = 1305
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = ((ctrl || stateno = 950 || stateno = 50 || stateno = 106) && helper(10002),command = "Hishou 1") || (movecontact && command = "Hishou 1")
triggerall = !(movecontact && (stateno = [600,639])) || (var(7) > 0 && helper(10000),var(14) = 5)
trigger1 = ctrl || stateno = 950 || stateno = 50 || stateno = 106
trigger1 = command != "holdup"
Trigger2 = stateno = 246 && (movecontact = [1,3])
Trigger3 = stateno = 600 && (movecontact = [1,3])
Trigger4 = stateno = 610 && (movecontact = [1,3])
Trigger5 = stateno = 620 && (movecontact = [1,3])
Trigger6 = stateno = 630 && (movecontact = [1,3])
trigger7 = stateno = 640 && (movecontact = [1,3])
trigger8 = stateno = 105
trigger9 = stateno = 310 && (movecontact = [1,3])
trigger10 = stateno = 320; && (movecontact = [1,3])
ignorehitpausetime = 1

;Hishou 2
[State -1]
type = ChangeState
value = 1300
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = ((ctrl || stateno = 950 || stateno = 50 || stateno = 106) && helper(10002),command = "Hishou 2") || (movecontact && command = "Hishou 2")
triggerall = !(movecontact && (stateno = [600,639])) || (var(7) > 0 && helper(10000),var(14) = 5)
trigger1 = ctrl || stateno = 950 || stateno = 50 || stateno = 106
trigger1 = command != "holdup"
Trigger2 = stateno = 246 && (movecontact = [1,3])
Trigger3 = stateno = 600 && (movecontact = [1,3])
Trigger4 = stateno = 610 && (movecontact = [1,3])
Trigger5 = stateno = 620 && (movecontact = [1,3])
Trigger6 = stateno = 630 && (movecontact = [1,3])
trigger7 = stateno = 640 && (movecontact = [1,3])
trigger8 = stateno = 105
trigger9 = stateno = 310 && (movecontact = [1,3])
trigger10 = stateno = 320; && (movecontact = [1,3])
ignorehitpausetime = 1

[state -1]
type = null;changestate
value = 1380
triggerall = !var(59) && helper(10000),var(5) > 0
triggerall = statetype = A
triggerall = ((ctrl || stateno = 950 || stateno = 50 || stateno = 106) && helper(10002),command = "Hishou 3") || (movecontact && command = "Hishou 3")
trigger1 = ctrl || stateno = 950 || stateno = 50 || stateno = 106
Trigger2 = stateno = 246 && (movecontact = [1,3])
Trigger3 = stateno = 600 && (movecontact = [1,3])
Trigger4 = stateno = 610 && (movecontact = [1,3])
Trigger5 = stateno = 620 && (movecontact = [1,3])
Trigger6 = stateno = 630 && (movecontact = [1,3])
trigger7 = stateno = 640 && (movecontact = [1,3])
trigger8 = stateno = 105
trigger9 = stateno = 310 && (movecontact = [1,3])
trigger10 = stateno = 320; && (movecontact = [1,3])
ignorehitpausetime = 1

[state -1]
type = changestate
value = 1380
triggerall = !var(59) && helper(10000),var(5) > 0
triggerall = statetype = A
triggerall = ((ctrl || stateno = 50 || stateno = 106) && helper(10002),command = "Hishou 3") || (movecontact && command = "Hishou 3")
trigger1 = ctrl || stateno = 50 || stateno = 106
Trigger2 = stateno = 246 && (movecontact = [1,3])
Trigger3 = stateno = 600 && (movecontact = [1,3]) && prevstateno = 50
Trigger4 = stateno = 610 && (movecontact = [1,3]) && prevstateno = 50
Trigger5 = stateno = 620 && (movecontact = [1,3]) && prevstateno = 50
Trigger6 = stateno = 630 && (movecontact = [1,3]) && prevstateno = 50
trigger7 = stateno = 640 && (movecontact = [1,3]) && prevstateno = 50
trigger8 = stateno = 105
trigger9 = stateno = 310 && (movecontact = [1,3])
trigger10 = stateno = 320; && (movecontact = [1,3])
ignorehitpausetime = 1

;Hishou 1
[State -1]
type = ChangeState
value = 40
triggerall = var(59) = 0
;triggerall = statetype != A
triggerall = helper(10000),var(5)
triggerall = stateno = 1302
trigger1 = command = "up"
trigger2 = command = "holdup"

;-------------------------------------------------------------------------------
;Patada KOF-98
[State -1]
type = ChangeState
value = 1450
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = (ctrl && helper(10002),command = "Patada KOF-98") || (movecontact && command = "Patada KOF-98")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400; && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1450
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "Patada KOF-98"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

;---------------------------------------------------------------------------
[State -1]
type = ChangeState
value = 1800
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A
triggerall = stateno != 1800
triggerall = command != "Kuusajin 1"
triggerall = command != "Kuusajin 2"
triggerall = (ctrl && helper(10002),command = "×Æ»ðÒu1") || (movecontact && command = "×Æ»ðÒu1")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1800
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "×Æ»ðÒu1"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

[State -1]
type = ChangeState
value = 1850
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A
triggerall = stateno != 1850
triggerall = command != "Kuusajin 1"
triggerall = command != "Kuusajin 2"
triggerall = (ctrl && helper(10002),command = "×Æ»ðÒu2") || (movecontact && command = "×Æ»ðÒu2")
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1850
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "×Æ»ðÒu2"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

[State -1]
type = ChangeState
value = 1900
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A
triggerall = stateno != 1900
triggerall = (ctrl && helper(10002),command = "DBy") || (movecontact && command = "DBy")
triggerall = numprojid(1902) = 0
trigger1 = ctrl
Trigger2 = stateno = 200 && (movecontact = [1,3])
trigger2 = 0
Trigger3 = stateno = 205 && (movecontact = [1,3])
Trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
Trigger5 = stateno = 215 && (movecontact = [1,3])
Trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger7 = stateno = 225 && (movecontact = [1,3])
Trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
Trigger10= stateno = 240 && (movecontact = [1,3]) && animelem = 7,>0
Trigger11= stateno = 241 && (movecontact = [1,3]) && animelem = 7,>0
Trigger12= stateno = 400 && (movecontact = [1,3])
Trigger13= stateno = 364 && (movecontact = [1,3])
Trigger14= stateno = 420 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = null;ChangeState
value = 1900
triggerall = var(59) = 0
triggerall = helper(10000),var(5)
triggerall = helper(10002),command = "DBy"
triggerall = statetype != A
;
trigger1 = stateno = 1302 && prevstateno = 1301
ignorehitpausetime = 1

[state -1]
type = null;changestate
value = 1910
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A && ctrl
trigger1 = helper(10002),command = "Hishou 1"

[state -1]
type = null;changestate
value = 1920
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A && ctrl
trigger1 = helper(10002),command = "Hishou 2"

[state -1]
type = null;changestate
value = 1930
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A && ctrl
trigger1 = helper(10002),command = "holddown" && command = "holdfwd" && command = "c"

[state -1]
type = null;changestate
value = 1935
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A && ctrl
trigger1 = helper(10002),command = "holddown" && command = "c"
trigger1 = command != "holdfwd" || command != "holdback"

[state -1]
type = null;changestate
value = 1950
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A && ctrl
trigger1 = helper(10002),command = "holdback" && command = "c"


;--------------------
;------  Pose  ------
;--------------------
[State -1]
type = ChangeState
value = 6070;195
triggerall = var(59) = 0
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall = Vel X = 0
trigger1 = command = "start"
trigger1 = statetype = S || statetype = C
trigger1 = ctrl = 1



[State -1]
type = ChangeState
value = 195
triggerall = var(59) = 0
triggerall = command = "start"
triggerall = Vel X = 0
triggerall = stateno != 195
triggerall = statetype = S
triggerall = ctrl = 1
Trigger1   = numhelper(6000)
Trigger2   = numhelper(6010)
Trigger3   = numhelper(6020)
Trigger4   = numhelper(6030)
Trigger5   = numhelper(6040)
Trigger6   = numhelper(6050)
Trigger7   = numhelper(6060)
trigger8   = var(57) <= 0

;--------------------
;------  Move  ------
;--------------------
[State -1, Run Fwd]
type = null;ChangeState
value = 100
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "FF"
trigger1 = ctrl

;
[State -1, Run Back]
type = null;ChangeState
value = 105
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "BB"
trigger1 = ctrl

;Recovery
[State -1,]
type = ChangeState
value = 365;5201
triggerall = var(59) = 0
triggerall = command = "recovery"
triggerall = alive = 1
trigger1 = CanRecover
trigger1 = stateno = 5050 && time > 15
trigger1 = pos y > -20
trigger1 = vel y > 0

;Power charge
[State -1,]
type = ChangeState
value = 9800 
triggerall = var(59) = 0
triggerall = power < 1000
triggerall = var(7) = 0
trigger1 = command = "charge 1"
trigger1 = command = "charge 2"
trigger1 = (statetype != A) && ctrl

;MAX MODE-EX
[State -1]
type = ChangeState
value = 4001
triggerall = var(59) = 0
triggerall = helper(10000),var(5) > 0
trigger1 = command = "MAX-1"
trigger1 = command = "MAX-2"
trigger1 = power >= 1000 && var(7) > 0
trigger1 = (statetype != A) && ctrl
trigger1 = helper(10000),var(14) = 1

;MAX MODE-98
[State -1]
type = ChangeState
value = 4000
triggerall = var(59) = 0
;triggerall = helper(10000),fvar(4) = 1
trigger1 = command = "MAX-1"
trigger1 = command = "MAX-2"
trigger1 = power >= 1000 && var(7) <= 0
trigger1 = (statetype != A) && ctrl
trigger2 = helper(10000),var(5) > 0
trigger2 = command = "MAX-1"
trigger2 = command = "MAX-2"
trigger2 = power >= 2000 && var(7) <= 0
trigger2 = stateno = [200,500]
trigger2 = movecontact
trigger2 = statetype != A

;---------------------
;------  Throw  ------
;---------------------
[State -1]
type = ChangeState
value = 800
triggerall = var(59) = 0
triggerall = statetype != A && statetype != C
triggerall = p2movetype != H
triggerall = p2bodydist x < 20
triggerall = command = "y"
triggerall = command = "holdfwd" || command = "holdback"
triggerall = command != "holddown"
trigger1 = ctrl

;
[State -1]
type = ChangeState
value = 801
triggerall = var(59) = 0
triggerall = statetype != A && statetype != C
triggerall = p2movetype != H
triggerall = p2bodydist x < 20
triggerall = command = "b"
triggerall = command = "holdfwd" || command = "holdback"
triggerall = command != "holddown"
trigger1 = ctrl 

;
[State -1]
type = ChangeState
value = 830
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A && statetype != C
triggerall = command = "holdfwd" && command = "start"
triggerall = command != "holddown"
trigger1 = ctrl || stateno = 101

;
[State -1]
type = ChangeState
value = 831
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A && statetype != C
triggerall = command = "holdback" && command = "start"
triggerall = command != "holddown"
trigger1 = ctrl || stateno = 101



;---------------------
;------  Avoid  ------
;---------------------
;----------------------
;--- Guarding Avoid ---
;----------------------
[State -1]
type = null;ChangeState
value = 361
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "z" || command = "ab"
trigger1 = ctrl
trigger2 = (stateno = 150 || stateno = 151) && power >= 1000
trigger3 = stateno = 101

;--------------
;--- Attack ---
;--------------
[State -1]
type = ChangeState
value = 364
triggerall = var(59) = 0
triggerall = statetype != A
trigger1 = stateno = 363 && helper(10002),var(7) = 1
ignorehitpausetime = 1

;------------
;--- Stay ---
;------------
[State -1]
type = ChangeState
value = 363
triggerall = var(59) = 0
triggerall = (var(7) > 0 && helper(10000),var(14) = 4) || helper(10000),var(5) = 2
triggerall = statetype != A
triggerall = command = "z"
triggerall = command != "holddown" || movecontact
triggerall = command != "holdfwd" || movecontact
triggerall = command != "holdback" || movecontact
trigger1 = ctrl
trigger2 = stateno = 101
trigger3 = stateno = 205 && (movecontact = [1,3])
trigger4 = stateno = 215 && (movecontact = [1,3])
trigger5 = stateno = 225 && (movecontact = [1,3])
trigger6 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger7 = stateno = 400 && (movecontact = [1,3])
trigger8 = stateno = 410 && (movecontact = [1,3])
trigger9 = stateno = 420 && (movecontact = [1,3])
trigger10 = stateno = 430 && (movecontact = [1,3])
ignorehitpausetime = 1

;------------
;--- Back ---
;------------
[State -1]
type = ChangeState
value = 360
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "ab" || command = "z" || command = "hold_z"
triggerall = (command = "holdback" && p2dist x >= 0) || (command = "holdfwd" && p2dist x < 0)
trigger1 = ctrl
trigger2 = stateno = 101


[State -1]
type = ChangeState
value = 370
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "ab" || command = "z" || command = "hold_z"
triggerall = command = "holdback"
triggerall = power >= 1000
trigger1 = stateno = 150 || stateno = 151
ignorehitpause = 0


;-----------------
;--- Forward 1 ---
;-----------------
[State -1]
type = ChangeState
value = 362
triggerall = var(59) = 0
triggerall = (var(7) > 0 && helper(10000),var(14) = 4) || helper(10000),var(5) = 2
triggerall = statetype != A
triggerall = command = "z" || command = "hold_z"
triggerall = command = "holddown"
trigger1 = ctrl
trigger2 = stateno = 101
trigger3 = stateno = 1002
trigger4 = stateno = 2007

;-----------------
;--- Forward 2 ---
;-----------------
[State -1]
type = ChangeState
value = 361
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "ab" || command = "z" || command = "hold_z"
;triggerall = command = "holdfwd"
triggerall = (command = "holdfwd" && p2dist x >= 0) || (command = "holdback" && p2dist x < 0)
trigger1 = ctrl
trigger2 = stateno = 101

[State -1]
type = ChangeState
value = 371
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "ab" || command = "z" || command = "hold_z"
triggerall = command = "holdfwd"
triggerall = power >= 1000
trigger1 = stateno = 150 || stateno = 151
ignorehitpause = 0



;----------------------------
;------  simple skill  ------
;----------------------------
[State -1]
type = ChangeState
value = 240
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "a"
triggerall = command != "holddown"
triggerall = command = "holdfwd"
trigger1 = ctrl
trigger2 = stateno = 52 || stateno = 101
trigger2 = animelem = 1, >= 1
trigger3 = stateno = 364 && (movecontact = [1,3])
ignorehitpausetime = 1

[State 220, 3]
type = ChangeState
value = 240
triggerall = var(59) = 0 && ishelper = 0
triggerall = helper(10002),var(21) = 240
trigger1 = stateno = 430 && animelem = 4

;
[State -1]
type = ChangeState
value = 241
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "a"
triggerall = command != "holddown"
triggerall = command = "holdfwd"
trigger1 = stateno = 200 && movecontact
trigger1 = 0
trigger2 = stateno = 205 && (movecontact = [1,3])
trigger3 = stateno = 210 && (movecontact = [1,3]) && anim = 211
trigger4 = stateno = 215 && (movecontact = [1,3])
trigger5 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger6 = stateno = 225 && (movecontact = [1,3])
trigger7 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger8 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger9 = stateno = 400 && (movecontact = [1,3])
trigger10 = stateno = 364 && (movecontact = [1,3])
trigger11 = stateno = 364 && (movecontact = [1,3])
ignorehitpausetime = 1


[State -1]
type = ChangeState
value = 310;245
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "x"
triggerall = command != "holddown"
triggerall = command = "holdfwd"
trigger1 = (var(7) > 0 && helper(10000),var(14) = 5) || helper(10000),var(5) = 2
trigger1 = stateno = [101,102]

[State -1]
type = ChangeState
value = 320;245
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "x"
triggerall = command != "holddown"
triggerall = command = "holdfwd"
;triggerall = (var(7) > 0 && helper(10000),var(14) = 5) || helper(10000),var(5) = 2
triggerall = helper(10000),var(5) = 2
trigger1 = ctrl
trigger1 = 0
trigger2 = stateno = 200 && movecontact
trigger2 = 0
trigger3 = stateno = 205 && (movecontact = [1,3])
trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
trigger5 = stateno = 215 && (movecontact = [1,3])
trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger7 = stateno = 225 && (movecontact = [1,3])
trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger10 = stateno = 400 && (movecontact = [1,3])
ignorehitpausetime = 1

[State -1]
type = ChangeState
value = 245
triggerall = var(59) = 0
triggerall = command = "x"
triggerall = command != "holddown"
triggerall = command = "holdfwd"
triggerall = statetype != A
;triggerall = var(7) <= 0 || (var(7) > 0 && helper(10000),var(14) != 5)
trigger1 = ctrl
trigger2 = stateno = 200 && movecontact
trigger2 = 0
trigger3 = stateno = 205 && (movecontact = [1,3])
trigger4 = stateno = 210 && (movecontact = [1,3]) && anim = 211
trigger5 = stateno = 215 && (movecontact = [1,3])
trigger6 = stateno = 220 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger7 = stateno = 225 && (movecontact = [1,3])
trigger8 = stateno = 230 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger9 = stateno = 235 && ((var(7) > 0 && (helper(10000),var(14) = [2,5])) || helper(10000),var(5) = 2) && (movecontact = [1,3])
trigger10 = stateno = 400 && (movecontact = [1,3])
trigger11 = stateno = [101,102]
trigger12 = stateno = 364 && (movecontact = [1,3])
ignorehitpausetime = 1


;----------------
;------ CD ------
;----------------
;Rescatada 1
[State -1]
type = ChangeState
value = 301
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype != A
triggerall = command = "holdfwd"
triggerall = command = "cd" || command = "c"
trigger1 = ctrl
trigger2 = stateno = 101

;Rescatada 1
[State -1]
type = ChangeState
value = 300
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "cd" || command = "c"
trigger1 = ctrl
trigger2 = stateno = 101

;Rescatada 2
[State -1]
type = ChangeState
value = 305
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "cd" || command = "c"
trigger1 = (stateno = 150 || stateno = 151) && power >= 1000
ignorehitpause = 0

;------------
;--- edit ---Hishou
;------------
[State -1]
type = ChangeState
value = 660
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype = A
triggerall = command = "cd" || command = "c"
triggerall = command = "holddown"
trigger1 = ctrl
trigger2 = stateno = 950 || stateno = 50


;Rescatada Aire
[State -1]
type = ChangeState
value = 640
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = command = "cd" || command = "c"
trigger1 = ctrl || stateno = 950 || stateno = 50



;-----------------------------
;------  state 205 200  ------
;-----------------------------
;----------
;---near---
;----------
[State -1,]
type = ChangeState
value = 205
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = p2bodydist x = [-58,28]
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = ctrl
trigger2 = stateno = 52 || stateno = 101
trigger2 = animelem = 1, >= 1
trigger3 = stateno = 410 && time = [6,9]
ignorehitpausetime = 1

;---------
;---far---
;---------
[State -1,]
type = ChangeState
value = 200
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = ctrl
trigger2 = stateno = 52 || stateno = 101
trigger2 = animelem = 1, >= 1
trigger3 = stateno = 410 && time = [6,9]
ignorehitpausetime = 1

;-----------------------------
;------  state 215 210  ------
;-----------------------------
;----------
;---near---
;----------
[State -1]
type = ChangeState
value = 215
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = p2bodydist x = [-58,28]
triggerall = command = "a"
triggerall = command != "holddown" && command != "holdfwd"
trigger1 = ctrl
trigger2 = stateno = 52 || stateno = 101
trigger2 = animelem = 1, >= 1

;---------
;---far---
;---------
[State -1]
type = ChangeState
value = 210
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "a"
triggerall = command != "holddown" && command != "holdfwd"
trigger1 = ctrl
trigger2 = stateno = 52 || stateno = 101
trigger2 = animelem = 1, >= 1
trigger3 = stateno = 410
trigger3 = time > 6

;-----------------------------
;------  state 225 220  ------
;-----------------------------
;----------
;---near---
;----------
[State -1]
type = ChangeState
value = 225
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = p2bodydist x = [-58,28]
triggerall = command = "y"
triggerall = command != "holddown"
trigger1 = ctrl
trigger2 = stateno = 52
trigger2 = animelem = 1, >= 1
trigger3 = stateno = 101

;---------
;---far---
;---------
[State -1]
type = ChangeState
value = 220
triggerall = var(59) = 0
triggerall = statetype != A
;triggerall = facing != enemy,facing
triggerall = command = "y"
triggerall = command != "holddown"
trigger1 = ctrl
trigger2 = stateno = 52
trigger2 = animelem = 1, >= 1
trigger3 = stateno = 101

;-----------------------------
;------  state 235 230  ------
;-----------------------------
;----------
;---near---
;----------
[State -1]
type = ChangeState
value = 235
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = p2bodydist x = [-58,28]
triggerall = command = "b"
triggerall = command != "holddown"
trigger1 = ctrl
trigger2 = stateno = 52
trigger2 = animelem = 1, >= 1
trigger3 = stateno = 101

;---------
;---far---
;---------
[State -1]
type = ChangeState
value = 230
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "b"
triggerall = command != "holddown"
trigger1 = ctrl
trigger2 = stateno = 52
trigger2 = animelem = 1, >= 1
trigger3 = stateno = 101



;-------------------------------
;------  state 400 ~ 430  ------
;-------------------------------
[State -1]
type = ChangeState
value = 400
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "x"
triggerall = command = "holddown"
trigger1 = ctrl
trigger2 = stateno = 101
trigger3 = stateno = 400 && movecontact
trigger3 = time > 7
trigger4 = stateno = 410 && movecontact
ignorehitpausetime = 1

;---------------------------------------
;
[State -1]
type = ChangeState
value = 410
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = ctrl
trigger2 = stateno = 101
trigger3 = stateno = 400 && movecontact
;trigger3 = time > 6
trigger4 = stateno = 410 && movecontact
;trigger4 = time > 6
ignorehitpausetime = 1

;---------------------------------------
;
[State -1]
type = ChangeState
value = 420
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "y"
triggerall = command = "holddown"
trigger1 = ctrl
trigger2 = stateno = 101

;---------------------------------------
;
[State -1]
type = ChangeState
value = 430
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = command = "b"
triggerall = command = "holddown"
trigger1 = ctrl
trigger2 = stateno = 101

;-------------------------------
;------  state 410 ~ *  ------
;-------------------------------
[state ]
type = changestate
value = 400
triggerall = var(59) = 0
trigger1 = stateno = 410 && animelem = 3,>=0
trigger1 = helper(10002),var(20) = 400
[state ]
type = changestate
value = 410
triggerall = var(59) = 0
triggerall = stateno = 410 && animelem = 3,>=0
trigger1 = helper(10002),var(20) = 410
[state ]
type = changestate
value = 205
triggerall = var(59) = 0
triggerall = stateno = 410 && animelem = 3,>=0
triggerall = p2bodydist x = [-56,26]
trigger1 = helper(10002),var(20) = 200
[state ]
type = changestate
value = 215
triggerall = var(59) = 0
triggerall = stateno = 410 && animelem = 3,>=0
triggerall = p2bodydist x = [-56,26]
trigger1 = helper(10002),var(20) = 210
[state ]
type = changestate
value = 200
triggerall = var(59) = 0
triggerall = stateno = 410 && animelem = 3,>=0
trigger1 = helper(10002),var(20) = 200
[state ]
type = changestate
value = 210
triggerall = var(59) = 0
triggerall = stateno = 410 && animelem = 3,>=0
trigger1 = helper(10002),var(20) = 210

;-------------------------------
;------  state 600 ~ 6 0  ------
;-------------------------------
[State -1]
type = ChangeState
value = 600
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = command = "x"
trigger1 = ctrl || stateno = 950 || stateno = 50



;---------------------------------------
;
[State -1]
type = ChangeState
value = 610
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = ctrl || stateno = 950 || stateno = 50
triggerall = command != "holddown"
trigger1 = command = "a" && command != "holdback"
trigger1 = p2bodydist x > 0
trigger2 = command = "a" && command != "holdfwd"
trigger2 = p2bodydist x <= 0

;--------------
;---New Edit---
;--------------
[State -1]
type = ChangeState
value = 615
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype = A
triggerall = ctrl || stateno = 950 || stateno = 50
triggerall = command != "holddown"
trigger1 = command = "a" && command = "holdback"
trigger1 = p2bodydist x > 0
trigger2 = command = "a" && command = "holdfwd"
trigger2 = p2bodydist x <= 0


;---------------------------------------
;
[State -1]
type = ChangeState
value = 620
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = command = "y" && command != "holddown"
trigger1 = ctrl || stateno = 950 || stateno = 50

;------------------
;--- 2002 style ---
;------------------
[State -1]
type = ChangeState
value = 621
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype = A
triggerall = command = "y" && command = "holddown"
trigger1 = ctrl || stateno = 950 || stateno = 50; || stateno = 106

;--------------
;---New Edit---
;--------------
[State -1]
type = ChangeState
value = 625
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype = A
trigger1 = command = "a" && command = "holddown"
trigger1 = ctrl || stateno = 950 || stateno = 50
trigger2 = command = "hold_a" && command = "holddown"
trigger2 = stateno = 627 && ctrl


;--------------
;---New Edit--- throw in air
;--------------
[State -1]
type = ChangeState
value = 850
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype = A
triggerall = command = "b" && command != "holddown"
trigger1 = stateno != 950
trigger1 = ctrl || stateno = 50

;
[State -1]
type = ChangeState
value = 630
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = command = "b" && command != "holddown"
trigger1 = ctrl || stateno = 950 || stateno = 50

;------------------
;--- 2002 style ---
;------------------
[State -1]
type = ChangeState
value = 636
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = statetype = A
triggerall = command = "b" && command = "holddown"
trigger1 = ctrl || stateno = 950 || stateno = 50

;================================================
;========  helper(10002) set for input  =========
;================================================

;---------------------------------------------
;------ hvar(1) set for FF BB preinput -------
;---------------------------------------------
[state -1]
type = changestate
value = 100
triggerall = var(59) = 0
triggerall = ctrl
triggerall = helper(10002),var(1) = 1
trigger1 = helper(10002),command = "holdfwd"
trigger1 = statetype != A

[state -1]
type = changestate
value = 105
triggerall = var(59) = 0
triggerall = ctrl
triggerall = helper(10002),var(1) = 2
trigger1 = helper(10002),command = "holdback"
trigger1 = statetype != A
;trigger1 = stateno = 20 && vel x < 0

[state -1]
type = changestate
value = 100
triggerall = var(59) = 0
triggerall = ctrl
trigger1 = statetype != A
trigger1 = helper(10002),command = "FF"

[state -1]
type = changestate
value = 105
triggerall = var(59) = 0
triggerall = ctrl
trigger1 = statetype != A
trigger1 = helper(10002),command = "BB"

;=======================================================
;========  helper(10002),var(2) set for input  =========
;=======================================================

[state -1]
type = changestate
value = helper(10002),var(2)
triggerall = var(59) = 0
triggerall = stateno = 52 && time >= 2
trigger1 = helper(10002),var(2) >= 300

;=======================================================
;========  helper(10002),var(3) set for input  =========
;=======================================================

[state -1]
type = changestate
value = helper(10002),var(3)
triggerall = var(59) = 0
triggerall = stateno = 950 || stateno = 50
trigger1 = helper(10002),var(3) > 0

;==================================================
;========  hvar(8) set for Cancel for CD  =========
;==================================================

[State -1]
type = ChangeState
value = helper(10002),var(8)
triggerall = var(59) = 0
triggerall = statetype != A
triggerall = helper(10002),var(8) > 0
trigger1 = anim = 300
trigger1 = stateno = 300 && animelem = 4
trigger2 = anim = 302
trigger2 = stateno = 300 && animelem = 10
trigger3 = stateno = 301 && animelem = 7
trigger4 = stateno = 420 && anim = 420 && animelem = 5
trigger5 = stateno = 420 && anim = 440 && animelem = 7;6
trigger6 = stateno = 430 && animelem = 4
ignorehitpausetime = 1


;============================================
;========  var(57) set for Striker  =========
;============================================
[state -1]
type = varset
var(57) = 0
trigger1 = roundstate = 1
trigger1 = numpartner
;persistent = 0

[state -1]
type = varset
var(57) = 2
;trigger1 = stateno = [161,199]
trigger1 = roundstate = 1
trigger1 = time = 2
trigger1 = stateno != 0
trigger2 = var(59)
trigger2 = var(58) > 0
;persistent = 0


[State -1]
type = Explod
triggerall = ishelper = 0
triggerall = numhelper(10000)
trigger1 = numexplod(7100) <= 0
trigger1 = teamside = 1
anim = 7100 + var(57) - 1
id = 7100
remove = 1
removetime = -1
sprpriority = 2
pos = 10 + helper(10000),var(32),90 + helper(10000),var(33)
postype = left
bindtime = -1
ownpal = 1
IgnoreHitPause = 1


[State -1]
type = Explod
triggerall = ishelper = 0
triggerall = numhelper(10000)
trigger1 = numexplod(7100) <= 0
trigger1 = teamside = 2
anim = 7100 + var(57) - 1
id = 7100
remove = -1
removetime = -1
sprpriority = 2
pos = -10 + helper(10000),var(32),90 + helper(10000),var(33)
postype = right
facing = -1
bindtime = -1
ownpal = 1
IgnoreHitPause = 1


[state -1]
type = RemoveExplod
id = 7100
triggerall = ishelper = 0
triggerall = roundstate = 1
trigger1 = var(57) <= 5
trigger1 = command = "fwd"
trigger1 = var(57) := var(57) + 1
trigger2 = var(57) >= 2
trigger2 = command = "back"
trigger2 = var(57) := var(57) - 1
trigger3 = var(57) <= 0
;
IgnoreHitPause = 1
persistent = 1


;----------------------------
;------- 2000 helper --------
;----------------------------
[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 1
;triggerall   = command = "holdfwd"
trigger1   = facing = 1 && p2bodydist x >= 0
trigger2   = facing = -1 && p2bodydist x < 0
Id         = 6000
Stateno    = 6003
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = left
pos = -90,0
name = "jae"

[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 1
;triggerall   = command = "holdfwd"
trigger1   = facing = -1 && p2bodydist x >= 0
trigger2   = facing = 1 && p2bodydist x < 0
Id         = 6000
Stateno    = 6003
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = right
pos = -90,0
name = "jae"



;----------------------------
;------- 2000 helper --------
;----------------------------
[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 2
;triggerall   = command = "holddown"
trigger1   = facing = 1 && p2bodydist x >= 0
trigger2   = facing = -1 && p2bodydist x < 0
Id         = 6010
Stateno    = 6014
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = left
pos = -100,0
name = "hwan"

[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 2
;triggerall   = command = "holddown"
trigger1   = facing = -1 && p2bodydist x >= 0
trigger2   = facing = 1 && p2bodydist x < 0
Id         = 6010
Stateno    = 6014
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = right
pos = -100,0
name = "hwan"

;----------------------------
;------- 2000 helper --------
;----------------------------
[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 3
;triggerall   = command = "holdback"
trigger1   = facing = 1 && p2bodydist x >= 0
trigger2   = facing = -1 && p2bodydist x < 0
Id         = 6020
Stateno    = 6023
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = left
pos = -100,0
name = "sueil"

[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 3
;triggerall   = command = "holdback"
trigger1   = facing = -1 && p2bodydist x >= 0
trigger2   = facing = 1 && p2bodydist x < 0
Id         = 6020
Stateno    = 6023
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = right
pos = -100,0
name = "sueil"


;----------------------------
;------- 2000 helper --------
;----------------------------
[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 4
;triggerall   = command = "holdback"
trigger1   = facing = 1 && p2bodydist x >= 0
trigger2   = facing = -1 && p2bodydist x < 0
Id         = 6030
Stateno    = 6033
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = left
pos = -100,0
name = "chang"

[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 4
;triggerall   = command = "holdback"
trigger1   = facing = -1 && p2bodydist x >= 0
trigger2   = facing = 1 && p2bodydist x < 0
Id         = 6030
Stateno    = 6033
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = right
pos = -100,0
name = "chang"

;----------------------------
;------- 2000 helper --------
;----------------------------
[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 5
;triggerall   = command = "holdback"
trigger1   = facing = 1 && p2bodydist x >= 0
trigger2   = facing = -1 && p2bodydist x < 0
Id         = 6040
Stateno    = 6043
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = left
pos = -100,0
name = "choi"

[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 5
;triggerall   = command = "holdback"
trigger1   = facing = -1 && p2bodydist x >= 0
trigger2   = facing = 1 && p2bodydist x < 0
Id         = 6040
Stateno    = 6043
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = right
pos = -100,0
name = "choi"


;----------------------------
;------- 2000 helper --------
;----------------------------
[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 6
;triggerall   = command = "holdback"
trigger1   = facing = 1 && p2bodydist x >= 0
trigger2   = facing = -1 && p2bodydist x < 0
Id         = 6050
Stateno    = 6053
Pos        = -50,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = left
pos = 0,0
name = "Maylee"

[State -1]
Type       = Helper
triggerall = var(59) = 0 && ishelper = 0 && roundstate > 1
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
triggerall   = command = "start" && var(57) = 6
;triggerall   = command = "holdback"
trigger1   = facing = -1 && p2bodydist x >= 0
trigger2   = facing = 1 && p2bodydist x < 0
Id         = 6050
Stateno    = 6053
Pos        = 50,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = right
pos = 0,0
name = "Maylee"


;-----------------------------------------------------------------------------

[state -1]
type = changestate
value = 100
triggerall = var(59) = 0 && ishelper = 0
trigger1 = stateno = 20
trigger1 = prevstateno = 1500
trigger1 = command = "holdfwd"
trigger1 = time > 3
trigger2 = stateno = 1500 && movecontact > 8
trigger2 = command = "holdfwd"


[State -1]
type = Explod
trigger1 = numexplod(58) = 0
trigger1 = life <= 0
trigger1 = var(58) != 1
IgnoreHitPause = 1
anim = 9999
removetime = -1
id = 58
sprpriority = -9
pos = 0,0
postype = p1
bindtime = -1
ownpal = 1

[state -1]
type = varset
var(58) = 1
triggerall = var(59)
trigger1 = var(58) = 0
trigger1 = life <= 0
trigger1 = numexplod(58)

[state -1]
type = varset
var(58) = 2
trigger1 = var(58) = 1
;trigger1 = life <= 0
;trigger1 = numexplod(58) = 0
trigger2 = palno = [7,12]


;Patada KOF-98
[State -1]
type = ChangeState
value = 1461
triggerall = (var(7) > 0 && (helper(10000),var(14) = 3 || helper(10000),var(14) = 5)) || helper(10000),var(5) = 2
triggerall = var(59) = 0
triggerall = command = "Patada KOF-98"
trigger1 = stateno != 1461
trigger1 = stateno = [1456,1470]
trigger1 = stateno != [1462,1463]
trigger1 = movecontact
trigger1 = stateno != 1465
trigger2 = stateno = 1465
trigger2 = animelem = 8,>0
trigger2 = movecontact
trigger3 = stateno = 1463
trigger3 = animelem = 2,>=0
trigger3 = movecontact

;Patada KOF-98
[State -1]
type = ChangeState
value = 1461
triggerall = var(59) = 0
trigger1 = command = "Patada KOF-98"
trigger1 = stateno = 1470 && movecontact
;trigger2 = command = "holdfwd" && command = "a"
;trigger2 = stateno = 1500 && movecontact = [1,3]
ignorehitpausetime = 1

[State -1]
type = ChangeState
value = 1105
triggerall = (var(7) > 0 && helper(10000),var(14) = 5) || helper(10000),var(5) = 2
triggerall = var(59) = 0
triggerall = command = "Kuusajin 2"
trigger1 = stateno = 1461
trigger1 = movecontact

[State -1]
type = ChangeState
value = 231
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = command = "x" || command = "y"
trigger1 = stateno = 1106
trigger1 = animelem = 11,>0
trigger1 = movecontact

[State -1]
type = ChangeState
value = 622
;triggerall = var(59) = 0
trigger1 = statetype = A
trigger1 = stateno = 232 && movecontact

[state -1]
type = velset
y = -3
trigger1 = stateno = 622 && time = 1
trigger1 = prevstateno = 232

[state -1]
type = changestate
value = 1465
triggerall = var(59) = 0
triggerall = command = "Patada KOF-98"
triggerall = command = "x"
trigger1 = stateno = 1456

[state -1]
type = changestate
value = 1462
triggerall = var(59) = 0
triggerall = command = "Patada KOF-98"
triggerall = command = "y"
triggerall = !(var(7) > 0 && helper(10000),var(14) = 3)
trigger1 = stateno = 1456


[state -1]
type = changestate
value = 1470
triggerall = var(59) = 0 && helper(10000),var(5) > 0
triggerall = command = "holdup" && command = "holdfwd"
triggerall = command = "a" || command = "b"
trigger1 = stateno = 1450 && animelem = 4,>=0

[state -1]
type = changestate
value = 1471
triggerall = var(59) = 0
triggerall = helper(10002),var(5) = 1
trigger1 = stateno = 1470 && animelem = 10

[state -1]
type = changestate
value = 430
triggerall = var(59)
trigger1 = stateno = [0,131]
trigger1 = enemynear,stateno = 200 && time > 1
trigger1 = enemynear,name = "nero_DMC4"


[state -1]
type = changestate
value = 1027
trigger1 = var(59) = 0 && helper(10000),var(5) > 0
trigger1 = stateno = 1106
trigger1 = helper(10002),var(6) = 1
trigger1 = animelem = 14


;Hishou 2
[State -1]
type = ChangeState
value = 1300
triggerall = var(59) = 0
triggerall = statetype = A
triggerall = command = "Hishou 2"
trigger1 = ctrl || stateno = 950 || stateno = 50
ignorehitpausetime = 1


;---------------------------------
;------ preinput beforejump ------
;---------------------------------
[State -1]
type = ChangeState
value = helper(10002),var(11)
triggerall = var(59) = 0 && ishelper = 0
triggerall = statetype = A
triggerall = helper(10002),var(11) > 0
trigger1 = stateno = 50 || stateno = 950
ignorehitpausetime = 1


;----------------------------
;------- 2000 helper --------
;----------------------------
[State -1]
Type       = Helper
;triggerall = var(59) = 0
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
trigger1   = facing = 1
trigger1   = stateno = 812 && p2stateno = 816 && animelem = 8
Id         = 6060
Stateno    = 6065
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = p2;left
pos = -90,0
name = "jae"

[State -1]
Type       = Helper
;triggerall = var(59) = 0
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
trigger1   = facing = -1
trigger1   = stateno = 812 && p2stateno = 816 && animelem = 8
Id         = 6060
Stateno    = 6065
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = p2
pos = -90,0
name = "jae"

;----------------------------
;------- 2000 helper --------
;----------------------------
[State -1]
Type       = Helper
;triggerall = var(59) = 0
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
trigger1   = facing = 1
trigger1   = stateno = 820 && p2stateno = 826 && animtime = -1
trigger1   = var(56) := 901
Id         = 6060
Stateno    = 6060
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = p2;left
pos = -90,0
name = "hwan"

[State -1]
Type       = Helper
;triggerall = var(59) = 0
Triggerall   = numhelper(6000) = 0 && var(57) > 0
Triggerall   = numhelper(6010) = 0
Triggerall   = numhelper(6020) = 0
Triggerall   = numhelper(6030) = 0
Triggerall   = numhelper(6040) = 0
Triggerall   = numhelper(6050) = 0
Triggerall   = numhelper(6060) = 0
trigger1   = facing = -1
trigger1   = stateno = 820 && p2stateno = 826 && animtime = -1
trigger1   = var(56) := 901
Id         = 6060
Stateno    = 6060
Pos        = 0,0
Helpertype = normal
Ownpal     = 1
Bind       = -1
Postype    = p2
pos = -90,0
name = "hwan"
